

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%   Aim: investigate if pre-whitening affects group level analyses when using a random
%%%%   effects model (via SPM).
%%%%   Written by:    Wiktor Olszowy, University of Cambridge
%%%%   Contact:       olszowyw@gmail.com
%%%%   Created:       May 2018 - August 2018
%%%%   Adapted from:  https://github.com/wanderine/ParametricMultisubjectfMRI/blob/master/SPM/run_random_group_analyses_onesamplettest_1.m
%%%%                  http://www.fil.ion.ucl.ac.uk/spm/data/face_rfx/
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


path_manage         = fgetl(fopen('path_manage.txt'));
path_scratch        = fgetl(fopen('path_scratch.txt'));
studies_parameters  = readtable([path_manage '/studies_parameters.txt']);
packages            = cellstr(['AFNI    '; 'FSL     '; 'SPM     '; 'SPM_FAST']);
exper_designs       = cellstr(['boxcar10'; 'boxcar12'; 'boxcar14'; 'boxcar16'; 'boxcar18'; 'boxcar20'; 'boxcar22'; 'boxcar24'; 'boxcar26'; 'boxcar28'; 'boxcar30'; 'boxcar32'; 'boxcar34'; 'boxcar36'; 'boxcar38'; 'boxcar40'; 'event1  '; 'event2  ']);
HRF_model           = 'gamma2_D';
smoothing           = 8;


addpath(genpath([path_manage '/matlab_extra_functions']));
addpath('/applications/spm/spm12_7219');


spm('Defaults', 'fMRI');
spm_jobman('initcfg');


for package_id         = 1:length(packages)

   package             = packages{package_id};

   for study_id        = 1:length(studies)

      study            = studies_parameters.study{study_id};
      abbr             = studies_parameters.abbr{study_id};
      task             = studies_parameters.task{study_id};

      %-following Eklund ea 2016, I only consider 1-sample t-test, where the sample is of size 20
      %-BMMR_checkerboard is of size 21, but for some very rare runs there were problems with SPM/FAST: the omnibus contrast did not return any voxels
      if strcmp(study, 'BMMR_checkerboard')
         no_subjects   = studies_parameters.n(study_id);
      else
         no_subjects   = 20;
      end

      for exper_design_id = 1:length(exper_designs)

         exper_design     = exper_designs{exper_design_id};

         path_output      = [path_scratch '/analysis_output_' study '/' package '/smoothing_' num2str(smoothing) '/exper_design_' exper_design '/HRF_' HRF_model];

         %-for CamCAN data, only some experimental designs
         if strcmp(study, 'CamCAN_sensorimotor') && ~strcmp(exper_design, 'boxcar10') && ~strcmp(exper_design, 'boxcar40') && ~strcmp(exper_design, 'event1') && ~strcmp(exper_design, 'event2')
            continue
         end

         %-for other datasets, no 'event1' and no 'event2'
         if ~strcmp(study, 'CamCAN_sensorimotor') && (strcmp(exper_design, 'event1') || strcmp(exper_design, 'event2'))
            continue
         end
         
         %-removing possible NaNs
         for subject_id   = 1:no_subjects
            subject       = ['sub-' abbr repmat('0', 1, 4-length(num2str(subject_id))) num2str(subject_id)];
            if exist([path_output '/' subject '/standardized_stats/coef1_FSL_SPM_masked_MNI.nii'] , 'file') == 2
               cd([path_output '/' subject '/standardized_stats']);
               system('fslmaths coef1_FSL_SPM_masked_MNI.nii -nan coef1_FSL_SPM_masked_MNI.nii.gz');
               system('rm coef1_FSL_SPM_masked_MNI.nii');
               system('gunzip coef1_FSL_SPM_masked_MNI.nii.gz');
            end
         end
         
         cd(path_output);

         system('mkdir group_analysis_random_effects');

         %-'coef1_FSL_SPM_masked_MNI.nii' were previously generated by 'make_group_analyses_mixed_effects.R'
         coef_maps                                                = cellstr(spm_select('FPListRec', fullfile(path_output), '^coef1_FSL_SPM_masked_MNI.nii'));

         %-BMMR_checkerboard is of size 21, but for some very rare runs there were problems with SPM/FAST: the omnibus contrast did not return any voxels
         if ~strcmp(study, 'BMMR_checkerboard')
            coef_maps                                             = coef_maps(1:no_subjects);
         end

         SPM_mat_location                                         = cellstr(fullfile(path_output, 'group_analysis_random_effects', 'SPM.mat'));

         clear jobs;
         
         jobs{1}.stats{1}.factorial_design.dir                    = cellstr(fullfile(path_output, 'group_analysis_random_effects'));
         jobs{1}.stats{1}.factorial_design.des.t1.scans           = coef_maps;
         jobs{1}.stats{1}.factorial_design.cov                    = struct('c', {}, 'cname', {}, 'iCFI', {}, 'iCC', {});
         %-using the explicit mask from the mixed effects run
         jobs{1}.stats{1}.factorial_design.masking.em             = {[path_output '/group_analysis_mixed_effects/mask.nii']};
         jobs{1}.stats{1}.factorial_design.globalc.g_omit         = 1;
         jobs{1}.stats{1}.factorial_design.globalm.gmsca.gmsca_no = 1;
         jobs{1}.stats{1}.factorial_design.globalm.glonorm        = 1;

         jobs{1}.stats{2}.fmri_est.spmmat                         = SPM_mat_location;

         jobs{1}.stats{3}.con.spmmat                              = SPM_mat_location;
         jobs{1}.stats{3}.con.consess{1}.tcon                     = struct('name', 'group 1 > 0', 'convec', 1, 'sessrep', 'none');

         jobs{1}.stats{4}.results.spmmat                          = SPM_mat_location;
         jobs{1}.stats{4}.results.conspec.contrasts               = Inf;
         jobs{1}.stats{4}.results.conspec.threshdesc              = 'FWE';
         
         spm_jobman('run', jobs);

         %-get t-map
         V           = spm_vol([path_output '/group_analysis_random_effects/spmT_0001.nii']);
         [tmap,aa]   = spm_read_vols(V);

         %-calculate cluster extent threshold
         [k,Pc]      = corrclusth(SPM, 0.001, 0.05, 1:100000);
         STAT        = 'T';
         df          = [1 SPM.xX.erdf];
         u           = spm_u(0.001, df, STAT);
         indices     = find(tmap>u);
         
         %-get the size of the largest cluster
         max_cluster = max_extent(tmap, indices);
         
         if max_cluster >= k
            indices     = find(tmap>u);
            disp([study ' ' num2str(smoothing) ' ' exper_design ': significant!']);
            disp('!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!');
            disp('!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!');
            disp('!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!');
         else
            indices     = '';
         end
         fid            = fopen('indices.txt', 'wt');
         fprintf(fid, '%8.0f\n', indices);

      end

   end

end

cd(path_manage)
